More Mathematical Functions
================================================

In [5]:
from numpy import *

<h4>Complex Numbers</h4>
<code>real</code>
<ul>
	<li> <code>real</code> returns the real elements of a complex array. 
	<li> <code>real</code> can be called either as a function <code>real(x)</code> or as an
	attribute <code>x.real</code>.
</ul>

<h4><code>imag</code></h4>
<ul>
	<li>  <code>imag()</code> returns the complex elements of a complex array.
	<li>  <code>imag()</code> can be called either as a function \texttt{imag(x)} or
	as an attribute <code>x.imag</code>.
</ul>

<h4><code>conj, conjugate<code></h4>
<ul>
	<li> <code>conj</code> returns the element-by-element complex conjugate for a complex array. 
	<li> <code>conj</code> can be called either as
	a function <code>conj(x)</code> or as a method <code>x.conj()</code>. 
	<li> <code>conjugate</code> is identical to <code>conj</code>.
</ul>


<h3>Sorting and Extreme Values</h3>

\subsubsection*{\texttt{sort}}
\texttt{sort} sorts the elements of an array. By default, it sorts using the last axis of x. 







In [8]:
x = random.randn(4,2)
x


array([[ 0.35358658,  0.96530544],
       [ 1.18474905,  0.09439589],
       [-0.68184884, -0.23306285],
       [ 0.77485772,  0.3741397 ]])

In [9]:
sort(x)


array([[ 0.35358658,  0.96530544],
       [ 0.09439589,  1.18474905],
       [-0.68184884, -0.23306285],
       [ 0.3741397 ,  0.77485772]])

<ul>
<li> <code>sort</code> uses an optional second
argument to indicate the axis to use for sorting (i.e. 0 for column-by-column, None for sorting all elements).
<li> 
<code>sort</code>does not alter the input when called as function, unlike the method version of <code>sort</code>.
</ul>



In [10]:

sort(x, 0)

array([[-0.68184884, -0.23306285],
       [ 0.35358658,  0.09439589],
       [ 0.77485772,  0.3741397 ],
       [ 1.18474905,  0.96530544]])

In [11]:


sort(x, axis=None)


array([-0.68184884, -0.23306285,  0.09439589,  0.35358658,  0.3741397 ,
        0.77485772,  0.96530544,  1.18474905])

<h4><code>ndarray.sort, argsort</code></h4>
<ul>
<li> <code>ndarray.sort</code> is a method for ndarrays which performs an in-place sort. 
<li> It economizes on memory use,
	although <code>x.sort()</code> is different from x after the function, unlike a call to <code>sort(x)</code>. 
<li> <code>x.sort()</code> sorts along
	the last axis by default, and takes the same optional arguments as <code>sort(x)</code>.
<li> <code>argsort</code> returns the indices
	necessary to produce a sorted array, but does not actually sort the data. 
<li> It is otherwise identical to <code>sort</code>,
	and can be used either as a function or a method.
</ul>



In [20]:
x = random.randn(3)
print(x)

print("\n sorted: \n")
print(sort(x))

print("\n x remains unsorted: \n")
print(x)

[-0.80743876 -1.32615976  0.42152585]

 sorted: 

[-1.32615976 -0.80743876  0.42152585]

 x remains unsorted: 

[-0.80743876 -1.32615976  0.42152585]


In [18]:
x.sort() # Inplace,changes x

x


array([-0.34247698, -0.04197494,  0.8521229 ])

In [ ]:
<h4>\texttt{max}, \texttt{amax}, \texttt{argmax}, \texttt{min}, \texttt{amin}, \texttt{argmin}</h4>
<ul>
<li> \texttt{max} and \texttt{min} return the maximum and minimum values from an array. 
<li> They take an optional second argument
which indicates the axis to use.
</ul>


In [22]:
x = random.randn(3,4)
print(x)
print("\n")
print(amax(x))



[[ 0.61653353  0.14028338  0.89959867 -0.89700305]
 [ 1.63687028 -2.39402378 -0.32861715  1.22070788]
 [-1.6741095   1.07466799  0.49449753 -0.10218869]]


1.63687028018


In [ ]:
x.max()

x.max(0)

x.max(1)


<ul>
	<li> <code>max()</code> and <code>min()</code> can only be used on arrays as methods. 
	<li> When used as a function, \texttt{amax} and \texttt{amin} must be used
	to avoid conflicts with the built-in functions <code>max()</code> and <code>min()</code>. 
	% <li> This behavior is also seen in around and round.
	<li> \texttt{argmax} and \texttt{argmin} return the \textbf{index} or indices of the maximum or minimum element(s). 
	<li> They are used in
	an identical manner to <code>max()</code> and <code>min()</code>, and can be used either as a function or method.
</ul>

In [ ]:
\subsubsection{\texttt{minimum}, \texttt{maximum}}
\texttt{maximum} and \texttt{minimum} can be used to compute the maximum and minimum of two arrays which are broadcastable.


In [ ]:
x = randn(4)

y = randn(4)

maximum(x,y)


<h3>Nan Functions</h3>
NaN function are convenience function which act similarly to their non-NaN versions, only ignoring NaN
values (rather than propagating) when computing the function.
<h4>nansum</h4>
<ul>
	<li> <code>nansum</code> is identical to sum, except that NaNs are ignored.
	<li> <code>nansum</code> can be used to easily generate other NaNfunctions,
	such as <code>nanstd</code> (standard deviation, ignoring nans) since variance can be implemented using 2
	sums.
</ul>

In [29]:
x = random.randn(4)
x[1] = nan
print(x)



[-0.36641779         nan -1.04133421  0.28222879]


In [30]:
print(sum(x))
print(nansum(x))

nan
-1.12552321821


In [31]:
nansum(x) / sum(x[logical_not(isnan(x))])



1.0

In [32]:
nansum(x) / sum(1-isnan(x)) # nanmean

-0.37517440606949809

<h4>nanmax, nanargmax, nanmin, nanargmin</h4>

<ul>
<li> <code>nanmax()</code>, <code>nanmin, nanargmax()</code> and <code>nanargmin()</code> are identical to their non-NaN counterparts, except that NaNs
are ignored.
</ul>

<h4>Functions and Methods/Properties</h4>
Many operations on NumPy arrays and matrices can be performed using a function or as a method of the
array. For example, consider \texttt{reshape}.


In [33]:
x = arange(25.0)
y = x.reshape((5,5))
print(y)



[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]]


In [34]:
z = reshape(x,(5,5))
print(z) 

[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]]
