In [1]:
import numpy as np

In [2]:
X = np.array([1,3,2,4,5,6])

In [3]:
type(X)

numpy.ndarray

In [4]:
np.sum(X)

21

In [6]:
np.exp(X)

array([   2.71828183,   20.08553692,    7.3890561 ,   54.59815003,
        148.4131591 ,  403.42879349])

In [7]:
# sigmoid function
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [8]:
sigmoid(X)

array([ 0.73105858,  0.95257413,  0.88079708,  0.98201379,  0.99330715,
        0.99752738])

In [ ]:
# Shannon entropy
# P
# 0.4, 0.3, 0.2, 0.1

# log



In [10]:
P = np.array([0.4, 0.3,0.2,0.1])

P * np.log(P)

array([-0.36651629, -0.36119184, -0.32188758, -0.23025851])

In [12]:
-np.sum(P * np.log(P))

1.2798542258336674

In [13]:
def entropy(P):
    return(-np.sum(P * np.log(P)))

In [14]:
entropy(P)

1.2798542258336674

In [15]:
np.log10(P)

array([-0.39794001, -0.52287875, -0.69897   , -1.        ])

In [16]:
np.log2(P)

array([-1.32192809, -1.73696559, -2.32192809, -3.32192809])

In [17]:
#Change of Base

np.sum(P)

0.99999999999999989

In [18]:
Y=np.array([0.5,0.4,0.3])

In [19]:
entropy(Y)

1.0742817243274154

In [ ]:
# Error Message
# After Error Message - Divide each element by Sum
# Remove Negative Values - abs

def entropy(P):
    if np.sum(P) != 1 :   # Might Trigger because of Round error
           print("not summing to one")
    return(-np.sum(P * np.log(P)))

In [20]:
np.abs(-0.8)

0.80000000000000004

In [22]:
np.abs(round(-0.8,3))

0.80000000000000004

In [23]:
np.random.rand(5)

array([ 0.20637742,  0.18726136,  0.88602032,  0.36535637,  0.52615994])

In [28]:
# simulate 100 rolls
# np.ceil, np.floor 
# sum it up

# Experiment
# One Trial - Outcome is sum of 100 Rolls
np.sum(np.ceil(6*np.random.rand(100)))

# Repeat this experiment 1000 times

339.0

In [44]:
N=1000000
collect=np.ones(N)

for i in range(N):
    collect[i] = np.sum(np.ceil(6*np.random.rand(100)))
    

In [47]:
np.min(collect)

270.0

In [46]:
len(collect[collect<300])

1488

In [ ]:
#p-value
# Type I error
# Type II error



#### Transform Shape

In [48]:
X = collect

In [49]:
X.shape

(1000000,)

In [50]:
type(X)

numpy.ndarray

In [52]:
Y = np.reshape(X,(1000,1000))

In [54]:
np.shape(Y)

(1000, 1000)

In [55]:
## Slice - first 10 rows and first 10 columns
Z= Y[:10,:10]

In [56]:
np.shape(Z)

(10, 10)

In [60]:
sum(Z,0)

array([ 3570.,  3469.,  3471.,  3481.,  3449.,  3528.,  3533.,  3489.,
        3535.,  3500.])

In [61]:
sum(Z,1)

array([ 3571.,  3470.,  3472.,  3482.,  3450.,  3529.,  3534.,  3490.,
        3536.,  3501.])

In [62]:
sum(Z)

array([ 3570.,  3469.,  3471.,  3481.,  3449.,  3528.,  3533.,  3489.,
        3535.,  3500.])

In [ ]:
# fliplr , triu, diag

In [72]:
x = X[:42]
np.random.shuffle(x)
x


array([ 340.,  346.,  365.,  338.,  361.,  369.,  363.,  308.,  361.,
        330.,  366.,  359.,  349.,  341.,  336.,  347.,  348.,  351.,
        348.,  352.,  345.,  376.,  387.,  347.,  375.,  324.,  351.,
        351.,  321.,  332.,  324.,  372.,  354.,  367.,  366.,  322.,
        341.,  374.,  363.,  355.,  351.,  317.])