In [ ]:
Set Functions
===================================

\subsubsection*{\texttt{unique}}
\texttt{unique} returns the unique elements in an array. It only operates on the entire array. An optional second
argument can be returned which contains the original indices of the unique elements.


In [3]:
from numpy import *
x = ceiling(10*random.randn(20)
unique(x)


SyntaxError: invalid syntax (<ipython-input-3-b5ab2395265c>, line 3)

In [4]:
y,ind = unique(x, True)
ind
	array([0, 2, 4], dtype=int64)
x.flat[ind]
	array([ 0.11335982, 0.26617443, 1.34424621])


IndentationError: unexpected indent (<ipython-input-4-651168b08a27>, line 3)

In [5]:
%---------------------------------------%
\subsubsection*{\texttt{in1d}}
\texttt{in1d} returns a Boolean array with the same size as the first input array indicating the elements which are
also in a second array.
\begin{framed}
	\begin{verbatim}
	>>> x = arange(10.0)
	>>> y = arange(5.0,15.0)
	>>> in1d(x,y)
	array([False, False, False, False, False, 
	True, True, True, True, True], dtype=bool)
	\end{verbatim}
\end{framed}

SyntaxError: unexpected character after line continuation character (<ipython-input-5-297fe51c6600>, line 2)

In [6]:
%---------------------------------------%
\subsubsection*{\texttt{intersect1d}}
\texttt{intersect1d} is similar to \texttt{in1d}, except that it returns the elements rather than a Boolean array, and only
unique elements are returned. It is equivalent to \texttt{unique(x.flat[in1d(x,y)])}.
\begin{framed}
	\begin{verbatim}
	>>> x = arange(10.0)
	>>> y = arange(5.0,15.0)
	>>> intersect1d(x,y)
	array([ 5., 6., 7., 8., 9.])
	\end{verbatim}
\end{framed}

SyntaxError: unexpected character after line continuation character (<ipython-input-6-f33d192b56b1>, line 2)

In [7]:



%---------------------------------------%
\subsubsection*{\texttt{union1d}}
\texttt{union1d} returns the unique set of elements in 2 arrays.
\begin{framed}
	\begin{verbatim}
	>>> x = arange(10.0)
	>>> y = arange(5.0,15.0)
	>>> union1d(x,y)
	array([ 0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 10.,
	11., 12., 13., 14.])
	\end{verbatim}
\end{framed}


SyntaxError: unexpected character after line continuation character (<ipython-input-7-afcfa492ed69>, line 5)

<h4><code>setdiff1d()</code></h4>
<ul>
<li> <code>setdiff1d()</code> returns the set of the elements which are only in the first array but not in the second array.
</ul>

In [11]:
x = range(10.0)
y = range(5.0,15.0)
setdiff1d(x,y)


TypeError: 'float' object cannot be interpreted as an integer

<h4><code>setxor1d()</code></h4>
<ul>
<li> <code>setxor1d()</code> returns the set of elements which are in one (and only one) of two arrays.
</ul>

In [9]:
x = arange(10.0)
y = arange(5.0,15.0)
setxor1d(x,y)


SyntaxError: unexpected character after line continuation character (<ipython-input-9-f087722891c0>, line 3)