In [12]:
import numpy as np
np.random.randint(0,15,size=10)

array([ 2, 12,  9,  0, 14, 14, 11,  6,  0, 11])

In [13]:
np.random.randint(0,20,size=10)

array([992, 118, 585, 724,  10, 126, 942, 905, 509, 210])

In [16]:
Samp = np.random.randint(0,20,size=10)
print(Samp)
print(len(Samp))

[ 5 12 18  8 13  3 19 12 19  7]
10


In [18]:
print(np.unique(Samp))
print(len(np.unique(Samp)))

[ 3  5  7  8 12 13 18 19]
8


In [19]:
# TRUE IF DUPLICATES PRESENT
len(Samp) != len(np.unique(Samp))

True

In [20]:
int(len(Samp) != len(np.unique(Samp)))

1

In [27]:
Samp2 = np.random.randint(0,100000,size=500)
int(len(Samp2) != len(np.unique(Samp2)))

0

In [28]:
# Samp2 = np.random.randint(1000,size=25)
# Answer= int(len(Samp2) != len(np.unique(Samp2)))
# print(Answer)
# type(Answer)

In [29]:
def anyDupl(x, y):
    Samp2 = np.random.randint(x,size=y)
    Answer= int(len(Samp2) != len(np.unique(Samp2)))
    return(Answer)
    

In [43]:
Count = 0
N=100000

type(Count)

for x in range(0, N):
    Count=Count+anyDupl(2400000,500)

print(Count)    
print(N)

4998
100000


In [41]:
Count = 0
N=5000
type(Count)
for x in range(1, N):
    Count=Count+anyDupl(200000,300)

print(Count)    
print(N)

1034
5000
