In [2]:
import numpy as np

#### Generate a random series of 0s and 1s

In [3]:
np.random.randint(0,2,size=5)

array([1, 0, 0, 0, 0])

#### Colour Coding

- use pandas Series

In [4]:
import pandas as pd

Colour=pd.Series(["red","black"])

In [5]:
X = np.random.randint(0,2,size=5)
Colour[X]

0      red
1    black
1    black
1    black
0      red
dtype: object

#### Generate 1000 spins of the wheel

In [6]:
N=1000
np.random.randint(0,2,size=N)[0:10]

array([1, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In [7]:
Colour[np.random.randint(0,2,size=N)]

0      red
0      red
0      red
1    black
0      red
1    black
0      red
1    black
1    black
1    black
0      red
1    black
0      red
1    black
0      red
...
1    black
0      red
0      red
0      red
1    black
0      red
0      red
1    black
1    black
1    black
0      red
1    black
1    black
1    black
1    black
Length: 1000, dtype: object

In [8]:
N=10000
SEQ = np.random.randint(0,2,size=N)
print(SEQ[0:50])


[0 0 1 0 0 1 1 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 1 1 1 1 0 1
 1 0 1 1 0 1 0 1 1 0 1 0 0]


In [9]:
SEQ[0] == SEQ[1]

True

In [10]:
y=0
SEQ[y] == SEQ[y+1]

True

In [11]:
SEQ[0:30]

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0])

In [12]:
for y in range(0, 10):
        y=int(SEQ[y] == SEQ[y+1])
        print '%d' % ( y)

1
0
0
1
0
1
1
0
1
0


In [13]:
REPNO = np.ones_like(SEQ)

print(len(REPNO))
print(REPNO[0:5])
type(REPNO)




10000
[1 1 1 1 1]


numpy.ndarray

In [14]:
for y in range(1, 16):
        if SEQ[y] == SEQ[y-1]:    # if same as previous
            REPNO[y]=REPNO[y-1]+1
        else:                     # if not same as previous Reset to 1 
            REPNO[y]=1

In [15]:
print(SEQ[1:15])
print(REPNO[1:15])
print(max(REPNO))

[0 1 0 0 1 1 1 0 0 1 1 1 1 0]
[2 1 1 2 1 2 3 1 2 1 2 3 4 1]
4


In [ ]:
N2=10000000
SEQ2 = np.random.randint(0,2,size=N2)
REPNO2=np.ones_like(SEQ2)

In [ ]:
for y in range(1, N2):
        if SEQ2[y] == SEQ2[y-1]:
            REPNO2[y]=REPNO2[y-1]+1
        else:
            REPNO2[y]=1

In [ ]:
print(max(REPNO2))