### Introduction to pandas Series



#### Preliminaries

In [1]:
# Preliminaries
# Imports
#  - not everything here is necessary for this particular exercise
#  - Saves some typing for these exercises.

from __future__ import division
from __future__ import print_function
from __future__ import print_function, division
from numpy import array
from numpy import sqrt
from pandas import Series
#from pandas import date_range 
import pandas
import scipy.stats as stats
from numpy import *
# End Imports


#### Create an numpy array (called it "a")

In [2]:
a = array([1.2, 2.33, 3.14, 4.56,5,6.2])
a

array([ 1.2 ,  2.33,  3.14,  4.56,  5.  ,  6.2 ])

In [3]:
# Some Information about "a"
print(len(a))
print(type(a))

6
<class 'numpy.ndarray'>


#### Create a pandas series 

In [4]:
mySeries = Series([0.1, 1.113, 2.63, 3.4, 4.6])
print(mySeries)

0    0.100
1    1.113
2    2.630
3    3.400
4    4.600
dtype: float64


In [5]:
## Convert our numpy array "a" into a Series
mySer2 = Series(a)
print(mySer2)

0    1.20
1    2.33
2    3.14
3    4.56
4    5.00
5    6.20
dtype: float64


In [6]:
len(mySer2)


6

In [7]:
print(type(mySer2))
print(type(a))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [8]:
s = Series([0.1, 1.2, 2.3, 3.4, 4.5], index = ['a','b','c','d','e'])
s

a    0.1
b    1.2
c    2.3
d    3.4
e    4.5
dtype: float64

In [9]:
s = Series([0.1, 1.2, 2.3, 3.4, 4.5], index = ['a','b','c','d','e'])
print(s['e'])

## Same as this
print(s[4])


4.5
4.5


In [10]:
print(s[['a','c']])

## Same as this
print(s[[0,2]])


a    0.1
c    2.3
dtype: float64
a    0.1
c    2.3
dtype: float64


In [11]:
print(s[:3])
print(s[s>2.5])

a    0.1
b    1.2
c    2.3
dtype: float64
d    3.4
e    4.5
dtype: float64


#### Selecting items with the index "a"

In [12]:
# s = Series([0.1, 1.2, 2.3, 3.4, 4.5], 
#    index = ['a', 'b', 'c', 'a', 'b'])
# First and Fourth items have index "a"
s['a']

0.10000000000000001

In [13]:
a = array([0.1, 1.2, 2.3, 3.4, 4.5])
a

array([ 0.1,  1.2,  2.3,  3.4,  4.5])

### Names Index for the Series

In [14]:
s = Series({'a': 0.1, 'b': 1.2, 'c': 2.3})
s * 2.0

a    0.2
b    2.4
c    4.6
dtype: float64

In [15]:
s - 1.0

a   -0.9
b    0.2
c    1.3
dtype: float64

In [16]:
s1 = Series({'a': 0.1, 'b': 1.2, 'c': 2.3})
s2 = Series({'a': 1.0, 'b': 2.0, 'c': 3.0})
s3 = Series({'c': 0.1, 'd': 1.2, 'e': 2.3})
s1 + s2

a    1.1
b    3.2
c    5.3
dtype: float64

In [17]:
s1 * s2

a    0.1
b    2.4
c    6.9
dtype: float64

In [18]:
s1 + s3

a    NaN
b    NaN
c    2.4
d    NaN
e    NaN
dtype: float64

In [19]:

s1 = Series([1.0,2,3],index=['a']*3)
s2 = Series([4.0,5],index=['a']*2)
s1 + s2



a    5.0
a    6.0
a    6.0
a    7.0
a    7.0
a    8.0
dtype: float64

In [20]:
s1 = Series([1.0,2,3])
print(s1.values)
print(s1.index)

[ 1.  2.  3.]
RangeIndex(start=0, stop=3, step=1)


In [21]:

s1.index = ['cat','dog','elephant']
s1.index

Index(['cat', 'dog', 'elephant'], dtype='object')

In [22]:
s1 = Series(arange(10.0,20.0))
print(s1)
s1.describe()


0    10.0
1    11.0
2    12.0
3    13.0
4    14.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64


count    10.00000
mean     14.50000
std       3.02765
min      10.00000
25%      12.25000
50%      14.50000
75%      16.75000
max      19.00000
dtype: float64

In [23]:
summ = s1.describe()
summ['mean']

14.5

In [24]:
s1 = Series(arange(1.0,6),index=['a','a','b','c','d'])
print(s1)
s1.drop('a')

a    1.0
a    2.0
b    3.0
c    4.0
d    5.0
dtype: float64


b    3.0
c    4.0
d    5.0
dtype: float64

In [25]:

s1 = Series(arange(1.0,4.0),index=['a','b','c'])
s2 = Series(arange(1.0,4.0),index=['c','d','e'])
s3 = s1 + s2

print(s3)
s3.dropna()




a    NaN
b    NaN
c    4.0
d    NaN
e    NaN
dtype: float64


c    4.0
dtype: float64

In [26]:
s1 = Series(arange(1.0,4.0),index=['a','b','c'])
s2 = Series(arange(1.0,4.0),index=['c','d','e'])
s3 = s1 + s2
s3.fillna(-1.0)

a   -1.0
b   -1.0
c    4.0
d   -1.0
e   -1.0
dtype: float64